name: Daily Fire Monitoring

on:
  schedule:
    # 12.00–16.45 WIB (05.00–09.45 UTC)
    - cron: "*/15 5-9 * * *"

    # 17.00 WIB (10.00 UTC)
    - cron: "0 10 * * *"

    # 18.00, 19.00, 20.00 WIB
    - cron: "0 11-13 * * *"

    # 21.00, 00.00, 03.00, 06.00, 09.00 WIB
    - cron: "0 14,17,20,23,2,5 * * *"

  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Python script
        env:
          GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
        run: python main.py
