name: Daily Fire Monitoring

on:
  schedule:
    # 15:00 WIB (08:00 UTC)
    - cron: "0 8 * * *"
    # 17:00 WIB (10:00 UTC)
    - cron: "0 10 * * *"
    # 19:00 WIB (12:00 UTC)
    - cron: "0 12 * * *"
  workflow_dispatch:
jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Python script
        env:
          GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
        run: python main.py
